import { Children, ReactNode } from 'react'
import { Navbar, Footer } from '../components'
import Head from 'next/head'

interface LayoutProps {
	children: ReactNode
	pageTitle: string
}

const Home = (props: LayoutProps) => {
	const { children, pageTitle } = props
	return (
		<div className="mx-auto max-w-[1280px]">
			<Head>
				<title> {pageTitle} </title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<Navbar />
			<div className="">{children}</div>
			<Footer />
		</div>
	)
}

export default Home
